name: mlflow_sklearn
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - scikit-learn==1.1.1
      - mlflow
      - pandas
      - git+https://github.com/oneconvergence/dkube.git@3.3.mp
      - boto3
